site_name: tracker
site_description: Webpages Tracker
repo_url: https://github.com/alexandroqc/cgiitrackerback
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/alexandroqc">alexandroqc</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
