# Generated by Django 2.1.7 on 2019-03-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='web_page',
        ),
        migrations.AddField(
            model_name='webpage',
            name='applications',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.Applications'),
            preserve_default=False,
        ),
    ]
