# Generated by Django 2.1.7 on 2019-03-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190308_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='id',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='urls',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
