# Generated by Django 2.1.7 on 2019-03-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_webpage_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=15)),
                ('netloc', models.CharField(max_length=150)),
                ('path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
    ]
